# Generated by Django 5.2.4 on 2025-07-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_bio_alter_user_profile_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
